# Generated by Django 4.2.1 on 2023-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='function_name',
            field=models.CharField(default='none', max_length=300),
            preserve_default=False,
        ),
    ]
